
name: Clockin-releaseEdition

on:
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]
  schedule:
    - cron: 1 16 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install bs4
    - name: SignIn
      run: |
        python ./post.py
